### ISSUE TITLE
Fix holes in the i18n

### ISSUE THREAD

**Issue by RaphGL** [RaphGL/Tuckr#41]
- [ ] Add i18n to table column names
The table columns are still english only, as I haven't figured out how to change the column name dynamically with tabled. (Note: consider moving to a simpler table generation library if necessary)

- [x] Add i18n to Y/N and Yes/No 
Probably would be something like this
```toml
[confirmation]
no = "no"
yes = "yes"
short_no = "n"
short_yes = "y"
```

- [x] Translate errors and confirmation prompts that are not translated
